/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.vs.client;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.Scanner;

public class App {

    private final static int port = 7000;
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        try(Socket s = new Socket("localhost", port)){
            DataInputStream in = new DataInputStream( s.getInputStream());
            DataOutputStream out = new DataOutputStream( s.getOutputStream());
            out.write(0);
            int response = in.read();

            if (response == 0) {
                System.out.println("Game has started.");

                for(int i = 0; i<3; i++) {
                    System.out.println("Make your guess: ");
                    int input = scanner.nextInt();
                    out.write(input);
                    int roundResponse = in.read();
                    if (roundResponse == 1) System.out.println("Guess " + input + " was correct. You won.");
                    if (roundResponse == 2) System.out.println("Guess " + input + " was wrong. " + (2 - i) + " guesses left.");
                    if (roundResponse == 9) System.out.println("Guess " + input + " was wrong. You ran out of guesses and lost the game.");
                    if (roundResponse == 9 || roundResponse == 1) break;
                }
            }

            scanner.close();

        }catch (Exception e) {
            scanner.close();
            throw new Error(e);
        }
    }
}
